import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import {CartProvider} from "../context/CartContext"
import {OrderProvider} from "../context/OrderContext"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "../context/AuthContext";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <AuthProvider>
              <CartProvider>
               <OrderProvider>
                 <Navbar />
                <main>{children}</main>
                <Footer />
               </OrderProvider>
              </CartProvider>   

          </AuthProvider>
      
      </body>
    </html>
  );
}
