name : "ci trendy"

on:
   push:
      branches: ["main"]
   pull_request:
      branches: ["main"]

jobs:
  build:
    # Use the latest stable Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Laravel
        working-directory: ./server
        run: composer install  


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm' 
          cache-dependency-path: ./client/package-lock.json
      
      - name: Install Package
        working-directory: ./client
        run: npm install && npm install lint && npm install test
        

      - name: Build container
        run: docker compose up -d --build


        
      - name: Run tests
        run: npm test

   

